<a href="https://colab.research.google.com/github/suyash-sm/Valorant/blob/master/final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

final = pd.read_csv('final.csv')

In [ ]:
ss=final

In [ ]:
ss.head(10)

,GameID,Map,PlayerName,Agent,PlayerTeam,EnemyTeam,ACS,Kills,Deaths,Assists,PlayerTeamRounds,EnemyTeamRounds,Winner
0,60894,Breeze,Reduxx,jett,Booster Seat Gaming,Pho Real,313.0,24.0,10.0,3.0,13.0,7.0,Booster Seat Gaming
1,60894,Breeze,ChurmZ,chamber,Booster Seat Gaming,Pho Real,227.0,16.0,10.0,7.0,13.0,7.0,Booster Seat Gaming
2,60894,Breeze,diaamond,sova,Booster Seat Gaming,Pho Real,226.0,17.0,9.0,8.0,13.0,7.0,Booster Seat Gaming
3,60894,Breeze,Boltzy,viper,Booster Seat Gaming,Pho Real,218.0,17.0,12.0,2.0,13.0,7.0,Booster Seat Gaming
4,60894,Breeze,Virtyy,skye,Booster Seat Gaming,Pho Real,80.0,5.0,13.0,3.0,13.0,7.0,Booster Seat Gaming
5,60894,Breeze,Cohburg,astra,Pho Real,Booster Seat Gaming,229.0,15.0,16.0,5.0,7.0,13.0,Booster Seat Gaming
6,60894,Breeze,evaD,sova,Pho Real,Booster Seat Gaming,203.0,12.0,14.0,6.0,7.0,13.0,Booster Seat Gaming
7,60894,Breeze,Bobovo,chamber,Pho Real,Booster Seat Gaming,173.0,12.0,16.0,2.0,7.0,13.0,Booster Seat Gaming
8,60894,Breeze,Dopai,skye,Pho Real,Booster Seat Gaming,125.0,9.0,15.0,1.0,7.0,13.0,Booster Seat Gaming
9,60894,Breeze,Zento,viper,Pho Real,Booster Seat Gaming,89.0,6.0,18.0,3.0,7.0,13.0,Booster Seat Gaming

In [ ]:
df=final
df=df.dropna()
df.isnull().sum()

In [ ]:
befor_encoding=df

In [ ]:
from sklearn.preprocessing import LabelEncoder
map = LabelEncoder()
df['Map'] = map.fit_transform(df['Map'])

player= LabelEncoder()
df['PlayerName'] =player.fit_transform(df['PlayerName'])

agent=LabelEncoder()
df['Agent']=agent.fit_transform(df['Agent'])

In [ ]:
import pickle
with open('map_encoder.pkl', 'wb') as f:
    pickle.dump(map, f)

In [ ]:
with open('Playername_encoder.pkl', 'wb') as f:
    pickle.dump(player, f)

In [ ]:
with open('agent_encoder.pkl', 'wb') as f:
    pickle.dump(agent, f)

In [ ]:
test = pd.DataFrame(columns=['C1', 'C2'])
test['C1']= df[['PlayerTeam', 'EnemyTeam']].stack().reset_index(drop=True)
new=LabelEncoder()
test['C2']=new.fit_transform(test['C1'])
test=test.drop_duplicates()
mapping = dict(zip(test['C1'], test['C2']))

# Replace the values in the 'Category' column with the corresponding values from df2
df['PlayerTeam'] = df['PlayerTeam'].map(mapping)
df['EnemyTeam'] = df['EnemyTeam'].map(mapping)
df['Winner'] = df['Winner'].map(mapping)

In [ ]:
df['PlayerTeamWin'] = df.apply(lambda row: 1 if row['Winner'] == row['PlayerTeam'] else 0, axis=1)
df['EnemyTeamWin'] = df.apply(lambda row: 1 if row['Winner'] == row['EnemyTeam'] else 0, axis=1)

In [ ]:
df['KDA'] = (df['Kills'] + df['Assists']) / df['Deaths'].replace(0,1)

In [ ]:
X = df[['GameID', 'Map', 'PlayerName', 'Agent','ACS','KDA','PlayerTeamWin']]
Xv=X.iloc[:,:-1].values
Yv=X.iloc[:,-1].values

In [ ]:
df.head(10)

,GameID,Map,PlayerName,Agent,PlayerTeam,EnemyTeam,ACS,Kills,Deaths,Assists,PlayerTeamRounds,EnemyTeamRounds,Winner,PlayerTeamWin,EnemyTeamWin,KDA
0,60894,2,3604,5,247,1253,313.0,24.0,10.0,3.0,13.0,7.0,247,1,0,2.700000
1,60894,2,810,3,247,1253,227.0,16.0,10.0,7.0,13.0,7.0,247,1,0,2.300000
2,60894,2,5483,14,247,1253,226.0,17.0,9.0,8.0,13.0,7.0,247,1,0,2.777778
3,60894,2,590,15,247,1253,218.0,17.0,12.0,2.0,13.0,7.0,247,1,0,1.583333
4,60894,2,4569,13,247,1253,80.0,5.0,13.0,3.0,13.0,7.0,247,1,0,0.615385
5,60894,2,844,0,1253,247,229.0,15.0,16.0,5.0,7.0,13.0,247,0,1,1.250000
6,60894,2,5641,14,1253,247,203.0,12.0,14.0,6.0,7.0,13.0,247,0,1,1.285714
7,60894,2,588,3,1253,247,173.0,12.0,16.0,2.0,7.0,13.0,247,0,1,0.875000
8,60894,2,1125,13,1253,247,125.0,9.0,15.0,1.0,7.0,13.0,247,0,1,0.666667
9,60894,2,4871,15,1253,247,89.0,6.0,18.0,3.0,7.0,13.0,247,0,1,0.500000

In [ ]:
df.to_csv('average.csv',index=False)

In [ ]:
scaler = StandardScaler()
Xv = scaler.fit_transform(Xv)

In [ ]:
with open('scaler_object.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(Xv, Yv, test_size=0.1, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
y_p= classifier.predict(X_test)
cm = confusion_matrix(y_test, y_p)
print(cm)
accuracy_score(y_test, y_p)
classifier.predict_proba(y_p)

[[9395 1080]
 [3719 1174]]

0.6877277459656429

In [ ]:
classifier.predict_proba(X_test)

array([[0.4, 0.6],
       [0.7, 0.3],
       [1. , 0. ],
       ...,
       [0.8, 0.2],
       [1. , 0. ],
       [0.9, 0.1]])

In [ ]:
with open('model.pkl', 'wb') as f:
    pickle.dump(classifier, f)

NameError: ignored